title: Sitio
tabs:

  # Pages
  pages:
    label:
      es: Páginas
      en: Pages
    icon: dashboard
    sections:

      # Pages
      pages:
        headline: Pages
        type: pages

  # Settings
  settings:
    label:
      es: Configuration
      en: Settings
    icon: settings
    columns:

      # Settings/Content
      content:
        type: fields
        width: 2/3
        fields:

          settingsLine:
            type: line

      # Settings/Sidebar
      sidebar:
        sticky: true
        width: 1/3
        sections:
          files:
            type: files
